### ISSUE TITLE
Cannot read property 'continuationContents' of undefined

### ISSUE THREAD

**Issue by hazycora** [GilgusMaximus/yt-comment-scraper#15]
Getting comments doesn't work at all, seemingly.
Error:
```
TypeError: Cannot read property 'continuationContents' of undefined
    at Function.getComments (/home/hazy/Documents/GitHub/tv.hazy.su/node_modules/yt-comment-scraper/src/Youtube-Scraper.js:36:61)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/hazy/Documents/GitHub/tv.hazy.su/js/pages/watch.js:150:24
```

**Comment by GilgusMaximus** [comment]
Sorry, but without more information on your usage of the module I cannot help you. The module is working in FreeTube, so it is definitely working correctly.

**Comment by stephan-dev** [comment]
I get the same error, on FreeTube (linux, v 0.12.0). Both local API and invidious API fail to fetch comments. It did work once or twice, but I don't know why.
`TypeError: Cannot read property 'continuationContents' of undefined`

**Comment by GilgusMaximus** [comment]
@stephan-dev this is fixed in the nightly builds of freetube.
And as you linked correctly, the cookie was added correctly. 

If you are not using the nightly builds, please do so, or wait a few days for the next release. We are cleaning the last things up over there to release v13.0.0.

*But* it very, very rarely can happen that comments do not load with a 403. But it is so rarely that it is not a problem of the code, but rather a problem of YouTube sometimes not checking the cookie or something else. Retrying then usually works

**Comment by stephan-dev** [comment]
@GilgusMaximus Thanks. By looking into the code I noticed the scraping is far from trivial. Ok so I was looking at the new code, while I used the previous version. Will definitely use the nightly build.
Thanks for the explanations. Now I found https://github.com/GilgusMaximus/yt-comment-scraper/pull/14
Do you mean that Electron has had the same consent cookie problem, and that they fixed it on their side?

**Comment by stephan-dev** [comment]
Nevermind, found your FreeTube PR ! https://github.com/FreeTubeApp/FreeTube/pull/1179

**Comment by GilgusMaximus** [comment]
Here is the commit on FreeTube from PrestoN. https://github.com/FreeTubeApp/FreeTube/commit/01da5277ee64dace1922c6d51a2af7c76223ef72

**Comment by hazycora** [comment]
@GilgusMaximus even just the following code doesn't work for me.
```js
const ytcm = require("yt-comment-scraper") 

const payload = {
  videoId: VIDEO_ID_HERE,
  sortByNewest: false,
  setCookie: false
}

ytcm.getComments(payload).then((data) =>{
    console.log(data);
}).catch((error)=>{
    console.log(error);
});
```

Previous replies are about FreeTube- I don't know if it's specifically relevant to my issue as I don't entirely understand the replies. Is this problem fixed in a nightly release of the module? Or is the fix specific to FreeTube? 

In case it's helpful in any sort, I'm located in the United States. Tried it on a VPS I have here as well to see if it was somehow specific to my network somehow or something and it didn't work as well.

**Comment by GilgusMaximus** [comment]
Yeah, the problem is that you have set the setCookie option to false. You need to set it to true, as mentioned in the readme, if you are not in an environment like Electron, where cookies cannot be handled by modules.

That should fix your problems

**Comment by hazycora** [comment]
Thanks!
I misread the readme to say the exact opposite, that setCookie should be false unless I was using something like Electron.
Upon re-reading it though, I have realized I was wrong. My mistake. 
It works just fine 👍🏻

**Comment by GilgusMaximus** [comment]
No problem, better ask questions than get stuck for hours ^^

Best regards,
Gilgus

**Comment by TentacleSama4254** [comment]
TypeError: Cannot read property 'continuationContents' of undefined
    at Function.getComments (C:\Users\inush\Music\lulu\node_modules\yt-comment-scraper\src\Youtube-Scraper.js:36:61)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by TentacleSama4254** [comment]
i set setCookie option to true and still this err.tried false too

**Comment by GilgusMaximus** [comment]
The question is what did you try? The code above?
