### ISSUE TITLE
[Not Issue] Is it possible to use proxy?

### ISSUE THREAD

**Issue by chdzma** [GilgusMaximus/yt-comment-scraper#18]
Hi,

I am just setting up a project and I would like to hide the real ip of the queries.
So I am trying to configure proxy, but I can't find the way.

For example in the node-ytdl-core project they do it this way:

```
const HttpsProxyAgent = require('https-proxy-agent');
const proxy = 'http://user:pass@111.111.111.111:8080';
const agent = HttpsProxyAgent(proxy);
const stream = ytdl('https://www.youtube.com/watch?v=aqz-KE-bpKQ', {  requestOptions: { agent },});
```

My last option is to fork and make a new function for it. But I would like to get out of doubt.

Thanks

**Comment by GilgusMaximus** [comment]
This should be rather easy to do. As it seems there is a simple proxy option available in [Axios](https://masteringjs.io/tutorials/axios/proxy), so I should be able to add it. I will add it with the other changes I mentioned before

**Comment by GilgusMaximus** [comment]
Okay, I added the proxy feature, though i have no proxy at hand to test it. If you want, you could test it with the source code installed as package and give me a quick feedback whether it works, before I publish the newest module version

**Comment by chdzma** [comment]
There is an error in the line HttpRequester.js: 28:47

> TypeError: Cannot set property 'password' of undefined
>     at new HttpRequester (/node_modules/yt-comment-scraper/src/HttpRequester.js:28:47)
>     at Function.getComments (/node_modules/yt-comment-scraper/src/Youtube-Scraper.js:13:25)
>     at channel (/controllers/youtube.controller.ts:94:26)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)`

In this code:

```
if (proxyData) {
        this.session.defaults["proxy"] = {};
        this.session.defaults.proxy.host = proxyData.host;
        this.session.defaults.proxy.port = proxyData.port;
        this.session.defaults.proxy.protocol = proxyData.protocol;
        if (proxyData.auth) {
          this.session.defaults.auth.password = proxyData.auth.username;
          this.session.defaults.auth.username = proxyData.auth.password;
        }
      }
```

I have tried changing fix it this way

```
 if (proxyData) {
    this.session.defaults["proxy"] = {};
    this.session.defaults.proxy.host = proxyData.host;
    this.session.defaults.proxy.port = proxyData.port;
    this.session.defaults.proxy.protocol = proxyData.protocol;
    if (proxyData.auth) {
      this.session.defaults['auth'] = {};
      this.session.defaults.auth.username = proxyData.auth.username;
      this.session.defaults.auth.password = proxyData.auth.password;
    }
  }
```

But the result is that you need authentication, it seems that the only thing that fails is to correctly define the authentication parameters (username, password)

If it solves it, you can notify me again, and I try it.

Thanks

**Comment by GilgusMaximus** [comment]
Ahh. Dumb mistake. Of course if the field is not defined previously, it will fail to assign children. 

You line of of code for auth should definitely fix it
